name: 'Set output variables'
description: 'Configures output variables for a workflow'
inputs:
  varFilePath:
    description: 'File path to variable file or directory. Defaults to ./.github/variables/* if none specified and runs against each file in that directory.'
    required: false
    default: ./.github/variables/*

  filterValue:
    description: 'String starting with'
    required: false
    default: '*'

runs:
  using: "composite"
  steps:
    - run: |
        filename='${{ inputs.varFilePath }}'
        filter='${{ inputs.filterValue }}'

        while read line; do
          if  [[ $line == $filter ]] ;
          then
              echo "$line" >> $GITHUB_OUTPUT
          fi
        done < $filename
      shell: bash