name: Set Environment Variables from file

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  setvariable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Environment Variables
        uses: ./.github/actions/set-enviroment-variable
        with:
          varFilePath: ./.github/variables/variables.env

      # - name: Set the value
      #   id: step_one
      #   run: |
      #     echo "action_state=yellow" >> $GITHUB_ENV
      # - name: Use the value
      #   id: step_two
      #   run: |
      #     echo "${{ env.action_state }}" # This will output 'yellow'

      # - name: See variable os
      #   shell: bash
      #   run: |
      #     echo "os=ubuntu-latest" >> $GITHUB_ENV
      #     echo "$os"

      # - name: See variable os
      #   shell: bash
      #   run: |
      #     echo "${{ env.os }}"


      - name: See all
        shell: bash
        run: |
          echo "$GITHUB_ENV"


  see:
    needs: setvariable
    runs-on: ubuntu-latest
    steps:
      - name: See variable
        shell: bash
        run: |
          echo "${{ env.OS }}"
          echo "$GITHUB_ENV"

  # deploy:
  #   name: Using variable from environment imported from file os = ${{ env.os }}
  #   needs: [setvariable, see]
  #   runs-on: ${{ env.os }}
  #   steps:
  #     - name: See
  #       shell: bash
  #       run: |
  #         echo ${{ env.os }}