name: Set Environment Variables from file

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  setvariable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: ./.github/actions/set-enviroment-variable
        with:
          varFilePath: ./.github/variables/variables.env

  see:
    needs: setvariable
    runs-on: ubuntu-latest
    steps:
      - name: See variable os
        shell: bash
        run: |
          echo ${{ env.os }}
          echo "$os"

      - name: See all
        shell: bash
        run: |
          printenv

  # deploy:
  #   name: Using variable from environment imported from file os = ${{ env.os }}
  #   needs: [setvariable, see]
  #   runs-on: ${{ env.os }}
  #   steps:
  #     - name: See
  #       shell: bash
  #       run: |
  #         echo ${{ env.os }}