name: Replace token

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cschleiden/replace-tokens@v1.3
        with:
          tokenPrefix: '$('
          tokenSuffix: ')'        
          files: '["**/*.js"]'
        env:
          token: https://token.somecdn.com/
          SECRET: ${{ secrets.SECRET }}
          
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: token.js
