#
# https://github.com/aquasecurity/trivy-action#using-trivy-to-scan-infrastucture-as-code
#
name: Trivy scan
on:
  workflow_dispatch:  
  push:
    branches:
      - main
  pull_request:
    branches: main
    types:
      - opened
      - synchronize
jobs:
  build:
    name: Trivy scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          ignore-unfixed: true
          format: 'sarif'
          hide-progress: false
          exit-code: '0' ### TODO: Change the exit code to '1' when all violations have been fixed.
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'